# NumPy basics

## 1. Creation

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
np.empty([2,3], dtype='int')

In [ ]:
np.zeros([2,3])


In [ ]:
np.arange(0,10,2, dtype='float64')

In [ ]:
np.linspace(0,10,6, dtype=float)

In [ ]:
X = np.array([[1,2,3],[4,5,6]])
X

function | usage 
---|---
np.asarray|exisiting arrays are not copied
np.asfarray| returns to float type. exisiting arrays are copied
np.astype(`type`)|returns to array with certain type. exisiting arrays are copied
np.copy| copies the array of original

In [ ]:
print(X)
Z = np.copy(X)
y = np.asfarray(X)
X[1] = 1
print(y)
print(X)
print(Z)

In [ ]:
y = X.astype(np.float64)
print(y)
X[:,0] = np.array([1,6])
print(y)

np.ones_like(), np.zeros_like()

In [ ]:
np.zeros_like(X)

#### np.random.noraml(centre, std, size)

In [ ]:
import mglearn
data = np.random.normal(50,10,100)
x = np.linspace(0,100, data.shape[0])
mglearn.discrete_scatter(x,data)  

In [ ]:
plt.hist(data, bins=10)
plt.show()

## 2. Manipulation

#### np.allclose(X,Y) returns True if none of the elements of X and Y are different. 
<br>np.isclose(X,Y) : returns True element-wise. 

In [ ]:
X = np.ones([2, 3, 4])
np.ones_like(X)

In [ ]:
Y = X.reshape(-1, 3, 2)

In [ ]:
np.allclose(X.reshape(-1, 3, 2), Y)

In [ ]:
label = X.reshape(-1,3,2) == Y
~label.ravel()

In [ ]:
label1 = np.isclose(X.reshape(-1,3,2), Y)

In [ ]:
assert np.allclose(label, label1)

In [ ]:
assert np.allclose(X.reshape(-1, 3, 2), Y)

## 3. NumPy I/O

In [1]:
import os
import numpy as np
os.getcwd()

'C:\\Users\\chsjk\\class2019Spring-master\\class2019Spring-master'

In [36]:
np.random.seed(10)
a = np.random.randint(0, 10, [2, 3])
b = np.random.random([2, 3])
np.savez("test", a, b)


In [31]:
os.getcwd()

'C:\\Users\\chsjk\\class2019Spring-master\\class2019Spring-master'

In [32]:
!ls -al test* #유닉스 명령코드

'ls'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [27]:
# del a, b #변수를 지우는 역할
%who

a	 b	 np	 npzfiles	 os	 subprocess	 


In [37]:
npzfiles = np.load("test.npz")
npzfiles.files

['arr_0', 'arr_1']

In [38]:
npzfiles['arr_0']

array([[9, 4, 0],
       [1, 9, 0]])

#### csv 파일 불러오기 넘파이로

In [55]:
data = np.loadtxt("regression.csv", delimiter=",", skiprows=1, dtype={'names':('X',"Y"), 'formats':('f', 'f')})
data.shape

(17,)

In [57]:
np.savetxt("regression_saved.csv", data, delimiter=",")
# !ls -al regression_saved.csv

## 4. Inspecting

In [58]:
arr = np.random.random([5,2,3])

In [59]:
print(type(arr))
print(len(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


<class 'numpy.ndarray'>
5
(5, 2, 3)
3
30
float64


## 5. Operations

### 5.1 Arithmetic

In [70]:
a = np.arange(1, 5)
b = np.arange(9, 5, -1)

In [72]:
print(a - b)
print(a * b)
print( a ,b)

[-8 -6 -4 -2]
[ 9 16 21 24]
[1 2 3 4] [9 8 7 6]


#### numpy의 array는 행렬과 다르기 때문에 곱의 계산 제대로 해주려면 np.matrix()사용.  matrix하는 순간 bracket이 두 개 들어감. 

In [73]:
a = np.matrix(a)
b = np.matrix(b)
a,b

(matrix([[1, 2, 3, 4]]), matrix([[9, 8, 7, 6]]))

In [79]:
a*b.T

matrix([[70]])

In [78]:
a * np.swapaxes(b,0,1)

matrix([[70]])

In [80]:
a.T * b

matrix([[ 9,  8,  7,  6],
        [18, 16, 14, 12],
        [27, 24, 21, 18],
        [36, 32, 28, 24]])

### 5.2 Comparison

In [81]:
a = np.arange(1, 10).reshape(3,3)
b = np.arange(9, 0, -1).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [82]:
a == b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [ ]:
a > b

### 5.3 Aggregate (sum, min, max, mean, median, std)

In [ ]:
a

In [ ]:
a.sum(), np.sum(a)

In [ ]:
a.sum(axis=0), np.sum(a, axis=0)

In [ ]:
a.sum(axis=1), np.sum(a, axis=1)

## Broadcasting

In [ ]:
a = np.arange(1, 25).reshape(4, 6)
a

In [ ]:
a + 100

In [ ]:
b = np.arange(6)
b

In [ ]:
a + b

In [ ]:
c = np.arange(4).reshape([4,1])
c

In [ ]:
a + c

## Array copying

In [ ]:
a = np.random.randint(0, 9, (3, 3))

In [ ]:
x = np.random.randint(0,10,(10,10))
List = [a for a in i for i in x]
Dict = {}
for i in set(List):
    Dict[i] = List.count(i)

In [ ]:
np.random.seed(0)
a = np.random.randint(0,4, (2,2))
np.flipud(a)

In [ ]:
a