### Starting Jupyter Notebook 

Jupyter Notebook is a web interface which supports notebook for scientists. It is one of the most widely used web server because it has various convenient functions and shortcut keys. For example,

-`heading` :`esc+#` (# refers to numbers). 
<br>-`help`: `ctrl + shift + p`
<br>-`run`: `esc + shift` or `esc + ctrl`
<br>- insert cell `above` and `below`: `esc + a` and `esc + b`
<br>- `markdown` : `esc + m`
<br>- `code`: `esc + y`

### Various Sequences and their features

> **Sequence** : A data structure which is listed in an order. An element in a sequence has an index.
<br> **Iterable** : An object capable of returning its members one at a time. It can conduct *membership test*<br>
 **mutable** : An object which elements can be changed and fixed.

type|feature|example
---|:---:|---
string|immutable<br>iterable|`'a','123','\n'`
list|mutable<br>iterable|`[1,2,3]. ['apple']`
tuple|immutable<br>iterable|`(1,2,3), (3,), ('a',)`
dictionary|mutable<br>iterable|`{'a':1,'b':2}`
range|immutable<br>iterable|`range(10)`
set|mutable<br>iterable|`{1,2,3}`

### Type

Python is a **object-oriented programming language.** Everything is formed as an object, and contains ***identity, type***, and ***value***

####  4 Types of number : integer, float, complex, boolean

1) Integer

In [17]:
a = 1; print(type(a))

<class 'int'>


2) Float

In [25]:
import math
a = math.sqrt(2); type(a) #sqrt() is a function for root

float

3) Complex

In [21]:
a = 1j;type(a)

complex

4) Boolean

In [34]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.allclose(np.vstack((a,b)), np.hstack((a,b)).reshape(2,3))
type(result)

bool

 Converting one type to another

In [28]:
a = 1.2; a = int(a); print(type(a)) # a = 1

<class 'int'>


**Indexing** : index is a positional order of an element in iterable. The order starts from 0 and goes on 1,2,3...
<br>**Slicing**: slicing is to select an element using its index and convert it. 

In [20]:
a = '123'; print(type(a)); print(a[1]) 

<class 'str'>
2


In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


If an object is **immutable**, its element ***cannot be converted using slicing.***

In [50]:
t = [[1,2,3], (1,2,3), '123']
for i in t:
    try:
        i[0] = 3
        print('{} has successfully converted'.format(type(i)))
    except:
        print('{} cannot be converted'.format(type(i)))

<class 'list'> has successfully converted
<class 'tuple'> cannot be converted
<class 'str'> cannot be converted


#### Dictionary


In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


#### List can contain both mutable and immutable.

In [53]:
a=[(1,2,3), (3,8,0)]  
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

#### However, set() can only contain immutable, because it hashes its elements.

In [54]:
a = [[1,2,3],'123', 34, set(), {'a':1}]
p = set()
for i in a:
    try:
        p.add(i)
        print('{} can be contained'.format(type(i)))
    except:
        print('{} is not hashable'.format(type(i)))

<class 'list'> is not hashable
<class 'str'> can be contained
<class 'int'> can be contained
<class 'set'> is not hashable
<class 'dict'> is not hashable


### Numpy 
<br>: Numpy is one of the most widely used library in Python. It makes arrays which is alternative of matrix. Numpy library is widely used in the field of linear algebra and machine learning

In [56]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [57]:
print(b*b) #technically, array is not a matrix. 

[1 4 9]


In [58]:
c = np.matrix(b) 
print(c)
print(type(c))

[[1 2 3]]
<class 'numpy.matrixlib.defmatrix.matrix'>


Matrix multiplication

In [59]:
c*c  # should convert it into (m*n) * (n*p) 

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

#### Numpy Transpose

In [74]:
import numpy as np
a1 = c.T
a2 = np.swapaxes(c, 0,1)
a3 = np.transpose(c)

assert np.allclose(a1,a2)
print(a3)

[[1]
 [2]
 [3]]
